# ----
# Site

title: HMTRC
url: "https://hyperpolarizedmri.ucsf.edu/"
baseurl:
google_analytics_key:
disqus_shortname:
newsletter_action:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: HP C-13 Imaging Parameters
author:UCSF HMTRC
  name: UCSF HMTRC
  email: hyperpolarizedmri@ucsf.edu
  twitter: # UCSFHMTRC
social:
  name: UCSF HMTRC
  links:
    - https://github.com/CloudCannon/base-jekyll-template

# -----
# Build

timezone: Etc/UTC

permalink: /:categories/:title/

plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"

# -----------
# CloudCannon

social_icons:
  - LinkedIn
  - Twitter
  - Email


types:
  - Document
  - Video

_comments:
